import type { editor } from "monaco-editor";

export interface ThemeMeta {
  id: string;
  label: string;
  base: "vs" | "vs-dark" | "hc-black";
}

export const THEMES: ThemeMeta[] = [
  { id: "kith-dark", label: "Kith Dark", base: "vs-dark" },
  { id: "one-dark-pro", label: "One Dark Pro", base: "vs-dark" },
  { id: "github-dark", label: "GitHub Dark", base: "vs-dark" },
  { id: "dracula", label: "Dracula", base: "vs-dark" },
  { id: "monokai", label: "Monokai", base: "vs-dark" },
  { id: "nord", label: "Nord", base: "vs-dark" },
  { id: "tokyo-night", label: "Tokyo Night", base: "vs-dark" },
  { id: "catppuccin-mocha", label: "Catppuccin Mocha", base: "vs-dark" },
  { id: "solarized-dark", label: "Solarized Dark", base: "vs-dark" },
  { id: "github-light", label: "GitHub Light", base: "vs" },
  { id: "solarized-light", label: "Solarized Light", base: "vs" },
  { id: "vs-dark", label: "VS Dark (built-in)", base: "vs-dark" },
  { id: "vs", label: "VS Light (built-in)", base: "vs" },
  { id: "hc-black", label: "High Contrast", base: "hc-black" },
];

type ThemeDef = editor.IStandaloneThemeData;

const THEME_DEFS: Record<string, ThemeDef> = {
  "kith-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6A737D", fontStyle: "italic" },
      { token: "keyword", foreground: "C792EA" },
      { token: "keyword.control", foreground: "C792EA" },
      { token: "string", foreground: "C3E88D" },
      { token: "number", foreground: "F78C6C" },
      { token: "type", foreground: "FFCB6B" },
      { token: "type.identifier", foreground: "FFCB6B" },
      { token: "variable", foreground: "EEFFFF" },
      { token: "function", foreground: "82AAFF" },
      { token: "operator", foreground: "89DDFF" },
      { token: "delimiter", foreground: "89DDFF" },
      { token: "tag", foreground: "F07178" },
      { token: "attribute.name", foreground: "FFCB6B" },
      { token: "attribute.value", foreground: "C3E88D" },
      { token: "constant", foreground: "F78C6C" },
      { token: "regexp", foreground: "C3E88D" },
    ],
    colors: {
      "editor.background": "#0A0A0F",
      "editor.foreground": "#EEFFFF",
      "editorLineNumber.foreground": "#3B3F51",
      "editorLineNumber.activeForeground": "#C792EA",
      "editor.selectionBackground": "#3D3D5C50",
      "editor.lineHighlightBackground": "#12121A",
      "editorCursor.foreground": "#FFCC00",
      "editorWhitespace.foreground": "#2B2F40",
      "editorIndentGuide.background": "#1E1E2E",
      "editorIndentGuide.activeBackground": "#3B3F51",
      "editorBracketMatch.background": "#3D3D5C40",
      "editorBracketMatch.border": "#C792EA60",
      "editor.findMatchBackground": "#C792EA30",
      "editor.findMatchHighlightBackground": "#C3E88D20",
      "editorSuggestWidget.background": "#12121A",
      "editorSuggestWidget.border": "#2B2F40",
      "editorSuggestWidget.selectedBackground": "#3D3D5C",
      "editorWidget.background": "#12121A",
      "editorWidget.border": "#2B2F40",
      "minimap.background": "#0A0A0F",
      "scrollbarSlider.background": "#3B3F5140",
      "scrollbarSlider.hoverBackground": "#3B3F5180",
      "scrollbarSlider.activeBackground": "#3B3F51C0",
    },
  },

  "one-dark-pro": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "5C6370", fontStyle: "italic" },
      { token: "keyword", foreground: "C678DD" },
      { token: "string", foreground: "98C379" },
      { token: "number", foreground: "D19A66" },
      { token: "type", foreground: "E5C07B" },
      { token: "type.identifier", foreground: "E5C07B" },
      { token: "variable", foreground: "E06C75" },
      { token: "function", foreground: "61AFEF" },
      { token: "operator", foreground: "56B6C2" },
      { token: "delimiter", foreground: "ABB2BF" },
      { token: "tag", foreground: "E06C75" },
      { token: "attribute.name", foreground: "D19A66" },
      { token: "attribute.value", foreground: "98C379" },
      { token: "constant", foreground: "D19A66" },
      { token: "regexp", foreground: "98C379" },
    ],
    colors: {
      "editor.background": "#282C34",
      "editor.foreground": "#ABB2BF",
      "editorLineNumber.foreground": "#495162",
      "editorLineNumber.activeForeground": "#ABB2BF",
      "editor.selectionBackground": "#3E4451",
      "editor.lineHighlightBackground": "#2C313C",
      "editorCursor.foreground": "#528BFF",
      "editorWhitespace.foreground": "#3B4048",
      "editorIndentGuide.background": "#3B4048",
      "editorIndentGuide.activeBackground": "#636B78",
      "editorBracketMatch.background": "#3E445180",
      "editorBracketMatch.border": "#528BFF60",
    },
  },

  "github-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "8B949E", fontStyle: "italic" },
      { token: "keyword", foreground: "FF7B72" },
      { token: "string", foreground: "A5D6FF" },
      { token: "number", foreground: "79C0FF" },
      { token: "type", foreground: "FFA657" },
      { token: "type.identifier", foreground: "FFA657" },
      { token: "variable", foreground: "FFA657" },
      { token: "function", foreground: "D2A8FF" },
      { token: "operator", foreground: "FF7B72" },
      { token: "delimiter", foreground: "C9D1D9" },
      { token: "tag", foreground: "7EE787" },
      { token: "attribute.name", foreground: "79C0FF" },
      { token: "attribute.value", foreground: "A5D6FF" },
      { token: "constant", foreground: "79C0FF" },
      { token: "regexp", foreground: "7EE787" },
    ],
    colors: {
      "editor.background": "#0D1117",
      "editor.foreground": "#C9D1D9",
      "editorLineNumber.foreground": "#484F58",
      "editorLineNumber.activeForeground": "#C9D1D9",
      "editor.selectionBackground": "#264F78",
      "editor.lineHighlightBackground": "#161B22",
      "editorCursor.foreground": "#58A6FF",
      "editorWhitespace.foreground": "#21262D",
      "editorIndentGuide.background": "#21262D",
      "editorIndentGuide.activeBackground": "#30363D",
    },
  },

  dracula: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6272A4", fontStyle: "italic" },
      { token: "keyword", foreground: "FF79C6" },
      { token: "string", foreground: "F1FA8C" },
      { token: "number", foreground: "BD93F9" },
      { token: "type", foreground: "8BE9FD", fontStyle: "italic" },
      { token: "type.identifier", foreground: "8BE9FD", fontStyle: "italic" },
      { token: "variable", foreground: "F8F8F2" },
      { token: "function", foreground: "50FA7B" },
      { token: "operator", foreground: "FF79C6" },
      { token: "delimiter", foreground: "F8F8F2" },
      { token: "tag", foreground: "FF79C6" },
      { token: "attribute.name", foreground: "50FA7B" },
      { token: "attribute.value", foreground: "F1FA8C" },
      { token: "constant", foreground: "BD93F9" },
      { token: "regexp", foreground: "F1FA8C" },
    ],
    colors: {
      "editor.background": "#282A36",
      "editor.foreground": "#F8F8F2",
      "editorLineNumber.foreground": "#6272A4",
      "editorLineNumber.activeForeground": "#F8F8F2",
      "editor.selectionBackground": "#44475A",
      "editor.lineHighlightBackground": "#44475A75",
      "editorCursor.foreground": "#F8F8F2",
      "editorWhitespace.foreground": "#44475A",
      "editorIndentGuide.background": "#44475A",
      "editorIndentGuide.activeBackground": "#6272A4",
      "editorBracketMatch.background": "#44475A80",
      "editorBracketMatch.border": "#FF79C660",
    },
  },

  monokai: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "88846F", fontStyle: "italic" },
      { token: "keyword", foreground: "F92672" },
      { token: "string", foreground: "E6DB74" },
      { token: "number", foreground: "AE81FF" },
      { token: "type", foreground: "66D9EF", fontStyle: "italic" },
      { token: "type.identifier", foreground: "A6E22E" },
      { token: "variable", foreground: "F8F8F2" },
      { token: "function", foreground: "A6E22E" },
      { token: "operator", foreground: "F92672" },
      { token: "delimiter", foreground: "F8F8F2" },
      { token: "tag", foreground: "F92672" },
      { token: "attribute.name", foreground: "A6E22E" },
      { token: "attribute.value", foreground: "E6DB74" },
      { token: "constant", foreground: "AE81FF" },
      { token: "regexp", foreground: "E6DB74" },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#F8F8F2",
      "editorLineNumber.foreground": "#90908A",
      "editorLineNumber.activeForeground": "#C2C2BF",
      "editor.selectionBackground": "#49483E",
      "editor.lineHighlightBackground": "#3E3D32",
      "editorCursor.foreground": "#F8F8F0",
      "editorWhitespace.foreground": "#464741",
      "editorIndentGuide.background": "#464741",
      "editorIndentGuide.activeBackground": "#767771",
    },
  },

  nord: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "616E88", fontStyle: "italic" },
      { token: "keyword", foreground: "81A1C1" },
      { token: "string", foreground: "A3BE8C" },
      { token: "number", foreground: "B48EAD" },
      { token: "type", foreground: "8FBCBB" },
      { token: "type.identifier", foreground: "8FBCBB" },
      { token: "variable", foreground: "D8DEE9" },
      { token: "function", foreground: "88C0D0" },
      { token: "operator", foreground: "81A1C1" },
      { token: "delimiter", foreground: "ECEFF4" },
      { token: "tag", foreground: "81A1C1" },
      { token: "attribute.name", foreground: "8FBCBB" },
      { token: "attribute.value", foreground: "A3BE8C" },
      { token: "constant", foreground: "B48EAD" },
      { token: "regexp", foreground: "EBCB8B" },
    ],
    colors: {
      "editor.background": "#2E3440",
      "editor.foreground": "#D8DEE9",
      "editorLineNumber.foreground": "#4C566A",
      "editorLineNumber.activeForeground": "#D8DEE9",
      "editor.selectionBackground": "#434C5ECC",
      "editor.lineHighlightBackground": "#3B4252",
      "editorCursor.foreground": "#D8DEE9",
      "editorWhitespace.foreground": "#434C5E80",
      "editorIndentGuide.background": "#434C5E",
      "editorIndentGuide.activeBackground": "#4C566A",
    },
  },

  "tokyo-night": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "565F89", fontStyle: "italic" },
      { token: "keyword", foreground: "9D7CD8" },
      { token: "string", foreground: "9ECE6A" },
      { token: "number", foreground: "FF9E64" },
      { token: "type", foreground: "2AC3DE" },
      { token: "type.identifier", foreground: "2AC3DE" },
      { token: "variable", foreground: "C0CAF5" },
      { token: "function", foreground: "7AA2F7" },
      { token: "operator", foreground: "89DDFF" },
      { token: "delimiter", foreground: "9ABDF5" },
      { token: "tag", foreground: "F7768E" },
      { token: "attribute.name", foreground: "7AA2F7" },
      { token: "attribute.value", foreground: "9ECE6A" },
      { token: "constant", foreground: "FF9E64" },
      { token: "regexp", foreground: "B4F9F8" },
    ],
    colors: {
      "editor.background": "#1A1B26",
      "editor.foreground": "#C0CAF5",
      "editorLineNumber.foreground": "#3B4261",
      "editorLineNumber.activeForeground": "#737AA2",
      "editor.selectionBackground": "#33467C",
      "editor.lineHighlightBackground": "#1E2030",
      "editorCursor.foreground": "#C0CAF5",
      "editorWhitespace.foreground": "#292E42",
      "editorIndentGuide.background": "#292E42",
      "editorIndentGuide.activeBackground": "#3B4261",
    },
  },

  "catppuccin-mocha": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6C7086", fontStyle: "italic" },
      { token: "keyword", foreground: "CBA6F7" },
      { token: "string", foreground: "A6E3A1" },
      { token: "number", foreground: "FAB387" },
      { token: "type", foreground: "89DCEB" },
      { token: "type.identifier", foreground: "F9E2AF" },
      { token: "variable", foreground: "CDD6F4" },
      { token: "function", foreground: "89B4FA" },
      { token: "operator", foreground: "94E2D5" },
      { token: "delimiter", foreground: "BAC2DE" },
      { token: "tag", foreground: "F38BA8" },
      { token: "attribute.name", foreground: "F9E2AF" },
      { token: "attribute.value", foreground: "A6E3A1" },
      { token: "constant", foreground: "FAB387" },
      { token: "regexp", foreground: "F5C2E7" },
    ],
    colors: {
      "editor.background": "#1E1E2E",
      "editor.foreground": "#CDD6F4",
      "editorLineNumber.foreground": "#45475A",
      "editorLineNumber.activeForeground": "#CDD6F4",
      "editor.selectionBackground": "#45475A",
      "editor.lineHighlightBackground": "#313244",
      "editorCursor.foreground": "#F5E0DC",
      "editorWhitespace.foreground": "#313244",
      "editorIndentGuide.background": "#313244",
      "editorIndentGuide.activeBackground": "#45475A",
    },
  },

  "solarized-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "586E75", fontStyle: "italic" },
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2AA198" },
      { token: "number", foreground: "D33682" },
      { token: "type", foreground: "B58900" },
      { token: "type.identifier", foreground: "B58900" },
      { token: "variable", foreground: "268BD2" },
      { token: "function", foreground: "268BD2" },
      { token: "operator", foreground: "859900" },
      { token: "delimiter", foreground: "93A1A1" },
      { token: "tag", foreground: "268BD2" },
      { token: "attribute.name", foreground: "93A1A1" },
      { token: "attribute.value", foreground: "2AA198" },
      { token: "constant", foreground: "CB4B16" },
      { token: "regexp", foreground: "DC322F" },
    ],
    colors: {
      "editor.background": "#002B36",
      "editor.foreground": "#839496",
      "editorLineNumber.foreground": "#586E75",
      "editorLineNumber.activeForeground": "#93A1A1",
      "editor.selectionBackground": "#073642",
      "editor.lineHighlightBackground": "#073642",
      "editorCursor.foreground": "#839496",
      "editorWhitespace.foreground": "#073642",
      "editorIndentGuide.background": "#073642",
      "editorIndentGuide.activeBackground": "#586E75",
    },
  },

  "github-light": {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6A737D", fontStyle: "italic" },
      { token: "keyword", foreground: "D73A49" },
      { token: "string", foreground: "032F62" },
      { token: "number", foreground: "005CC5" },
      { token: "type", foreground: "6F42C1" },
      { token: "type.identifier", foreground: "6F42C1" },
      { token: "variable", foreground: "E36209" },
      { token: "function", foreground: "6F42C1" },
      { token: "operator", foreground: "D73A49" },
      { token: "delimiter", foreground: "24292E" },
      { token: "tag", foreground: "22863A" },
      { token: "attribute.name", foreground: "6F42C1" },
      { token: "attribute.value", foreground: "032F62" },
      { token: "constant", foreground: "005CC5" },
      { token: "regexp", foreground: "032F62" },
    ],
    colors: {
      "editor.background": "#FFFFFF",
      "editor.foreground": "#24292E",
      "editorLineNumber.foreground": "#BABBBC",
      "editorLineNumber.activeForeground": "#24292E",
      "editor.selectionBackground": "#0366D625",
      "editor.lineHighlightBackground": "#F6F8FA",
      "editorCursor.foreground": "#044289",
      "editorWhitespace.foreground": "#D1D5DA",
      "editorIndentGuide.background": "#EFF2F5",
      "editorIndentGuide.activeBackground": "#D7DDE3",
    },
  },

  "solarized-light": {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "93A1A1", fontStyle: "italic" },
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2AA198" },
      { token: "number", foreground: "D33682" },
      { token: "type", foreground: "B58900" },
      { token: "type.identifier", foreground: "B58900" },
      { token: "variable", foreground: "268BD2" },
      { token: "function", foreground: "268BD2" },
      { token: "operator", foreground: "859900" },
      { token: "delimiter", foreground: "586E75" },
      { token: "tag", foreground: "268BD2" },
      { token: "attribute.name", foreground: "586E75" },
      { token: "attribute.value", foreground: "2AA198" },
      { token: "constant", foreground: "CB4B16" },
      { token: "regexp", foreground: "DC322F" },
    ],
    colors: {
      "editor.background": "#FDF6E3",
      "editor.foreground": "#657B83",
      "editorLineNumber.foreground": "#93A1A1",
      "editorLineNumber.activeForeground": "#586E75",
      "editor.selectionBackground": "#EEE8D5",
      "editor.lineHighlightBackground": "#EEE8D5",
      "editorCursor.foreground": "#657B83",
      "editorWhitespace.foreground": "#EEE8D5",
      "editorIndentGuide.background": "#EEE8D5",
      "editorIndentGuide.activeBackground": "#93A1A1",
    },
  },
};

export function registerThemes(monaco: typeof import("monaco-editor")) {
  for (const [id, data] of Object.entries(THEME_DEFS)) {
    monaco.editor.defineTheme(id, data);
  }
}
