export const colors = {
  surface: 'var(--sys-surface)',
  surfaceDim: 'var(--sys-surface-dim)',
  surfaceContainerLowest: 'var(--sys-surface-container-lowest)',
  surfaceContainerLow: 'var(--sys-surface-container-low)',
  surfaceContainer: 'var(--sys-surface-container)',
  surfaceContainerHigh: 'var(--sys-surface-container-high)',
  surfaceContainerHighest: 'var(--sys-surface-container-highest)',
  surfaceBright: 'var(--sys-surface-bright)',
  background: 'var(--sys-background)',
  primary: 'var(--sys-primary)',
  onPrimary: 'var(--sys-on-primary)',
  primaryContainer: 'var(--sys-primary-container)',
  onPrimaryContainer: 'var(--sys-on-primary-container)',
  secondary: 'var(--sys-secondary)',
  onSecondary: 'var(--sys-on-secondary)',
  secondaryContainer: 'var(--sys-secondary-container)',
  onSecondaryContainer: 'var(--sys-on-secondary-container)',
  tertiary: 'var(--sys-tertiary)',
  onTertiary: 'var(--sys-on-tertiary)',
  tertiaryContainer: 'var(--sys-tertiary-container)',
  onTertiaryContainer: 'var(--sys-on-tertiary-container)',
  error: 'var(--sys-error)',
  onError: 'var(--sys-on-error)',
  errorContainer: 'var(--sys-error-container)',
  onErrorContainer: 'var(--sys-on-error-container)',
  onSurface: 'var(--sys-on-surface)',
  onSurfaceVariant: 'var(--sys-on-surface-variant)',
  onBackground: 'var(--sys-on-background)',
  outline: 'var(--sys-outline)',
  outlineVariant: 'var(--sys-outline-variant)',
  borderDefault: 'var(--sys-border-default)',
  glassBg: 'var(--sys-glass-bg)',
  glassBorder: 'var(--sys-glass-border)',
  steelGradStart: 'var(--color-steel-grad-start)',
  steelGradEnd: 'var(--color-steel-grad-end)',
  success: '#34d399',
  warning: '#fbbf24',
  danger: '#f87171',
} as const;

export const rawColors = {
  dark: {
    background: '#090C12',
    surfaceContainerLowest: '#0d1117',
    surfaceContainerLow: '#101721',
    surfaceContainer: '#141c27',
    surfaceContainerHigh: '#1a2535',
    surfaceContainerHighest: '#202d3f',
    surface: '#111827',
    primary: '#8FD9FF',
    secondary: '#A78BFA',
    tertiary: '#F472B6',
    onSurface: '#F2F7FB',
    onSurfaceVariant: '#C4D0DC',
    outline: '#2a3a50',
  },
  light: {
    background: '#F2F5F8',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f8fafc',
    surfaceContainer: '#f1f5f9',
    surfaceContainerHigh: '#e8edf4',
    surfaceContainerHighest: '#dde4ed',
    surface: '#ffffff',
    primary: '#1A8FC4',
    secondary: '#7C3AED',
    tertiary: '#DB2777',
    onSurface: '#0E1420',
    onSurfaceVariant: '#4A5568',
    outline: '#cbd5e1',
  },
} as const;

export const radius = {
  hero: 'var(--sys-radius-hero)',
  module: 'var(--sys-radius-module)',
  lg: 'var(--sys-radius-lg)',
  md: 'var(--sys-radius-md)',
  sm: 'var(--sys-radius-sm)',
  xs: 'var(--sys-radius-xs)',
  pill: 'var(--sys-radius-pill)',
} as const;

export const rawRadius = {
  hero: 32,
  module: 28,
  lg: 20,
  md: 16,
  sm: 12,
  xs: 8,
} as const;

export const shadows = {
  sm: 'var(--sys-shadow-sm)',
  md: 'var(--sys-shadow-md)',
  lg: 'var(--sys-shadow-lg)',
  glowPrimary: 'var(--sys-shadow-glow-primary)',
  glowSecondary: 'var(--sys-shadow-glow-secondary)',
} as const;

export const motion = {
  fast: { duration: 0.15, ease: [0.25, 0.1, 0.25, 1] },
  normal: { duration: 0.25, ease: [0.25, 0.1, 0.25, 1] },
  slow: { duration: 0.4, ease: [0.25, 0.1, 0.25, 1] },
  spring: { type: 'spring' as const, stiffness: 300, damping: 30 },
  springGentle: { type: 'spring' as const, stiffness: 200, damping: 25 },
} as const;

export const zIndex = {
  base: 0,
  dropdown: 10,
  sticky: 20,
  overlay: 30,
  modal: 40,
  toast: 50,
  tooltip: 60,
} as const;

export const agentColors: Record<string, string> = {
  ceo: 'var(--sys-primary)',
  cpo: 'var(--sys-secondary)',
  cto: 'var(--sys-tertiary)',
  cdo: 'var(--sys-tertiary)',
  cfo: '#34d399',
  cmo: '#fbbf24',
  coo: 'var(--sys-primary)',
  ciso: '#f87171',
  synthesizer: 'var(--sys-primary)',
  intent: 'var(--sys-secondary)',
  layout: 'var(--sys-secondary)',
  component: 'var(--sys-secondary)',
  code: 'var(--sys-primary)',
  patch: '#fbbf24',
  validation: '#34d399',
  design: 'var(--sys-tertiary)',
  sandbox: 'var(--sys-secondary)',
  deploy: '#34d399',
} as const;

export const statusColors: Record<string, string> = {
  draft: 'var(--sys-on-surface-variant)',
  ideation: 'var(--sys-secondary)',
  executive_review: 'var(--sys-secondary)',
  csuite_pending: '#fbbf24',
  csuite_running: 'var(--sys-secondary)',
  csuite_complete: '#34d399',
  planning: 'var(--sys-secondary)',
  designing: 'var(--sys-tertiary)',
  capability_gate: '#fbbf24',
  waiting_for_secrets: '#fbbf24',
  generating_code: 'var(--sys-primary)',
  building: 'var(--sys-primary)',
  repairing: '#fbbf24',
  ready_for_preview: '#34d399',
  deploy_ready: '#34d399',
  deployed: '#34d399',
  failed: 'var(--sys-error)',
} as const;
