"""replace fly columns with deno_project_id

Revision ID: eba5a71728b5
Revises: 20260303_0003
Create Date: 2026-03-04 14:39:21.442714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba5a71728b5'
down_revision: Union[str, Sequence[str], None] = '20260303_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS ix_generated_ideas_global_claimed_by ON generated_ideas_global (claimed_by)")
    op.execute("ALTER TABLE projects ADD COLUMN IF NOT EXISTS deno_project_id VARCHAR")
    op.execute("DROP INDEX IF EXISTS ix_projects_fly_app_name")
    op.execute("CREATE INDEX IF NOT EXISTS ix_projects_deno_project_id ON projects (deno_project_id)")
    op.execute("ALTER TABLE projects DROP COLUMN IF EXISTS fly_machine_ipv6")
    op.execute("ALTER TABLE projects DROP COLUMN IF EXISTS fly_app_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fly_app_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('fly_machine_ipv6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_deno_project_id'), table_name='projects')
    op.create_index(op.f('ix_projects_fly_app_name'), 'projects', ['fly_app_name'], unique=True)
    op.drop_column('projects', 'deno_project_id')
    op.drop_index(op.f('ix_generated_ideas_global_claimed_by'), table_name='generated_ideas_global')
    # ### end Alembic commands ###
